//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MattEland.Ani.Alfred.WPF.Properties {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MattEland.Ani.Alfred.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred:
        ///
        ///{0} {1}
        ///
        ///Do you want to continue running this application?.
        /// </summary>
        public static string App_OnUnhandledException_Message {
            get {
                return ResourceManager.GetString("App_OnUnhandledException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string App_OnUnhandledException_Unhandled_Error {
            get {
                return ResourceManager.GetString("App_OnUnhandledException_Unhandled_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has loaded..
        /// </summary>
        public static string AppOnlineLogMessage {
            get {
                return ResourceManager.GetString("AppOnlineLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically starting Alfred.
        /// </summary>
        public static string AutoStartAlfredLogMessage {
            get {
                return ResourceManager.GetString("AutoStartAlfredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        public static string ConsoleHeader {
            get {
                return ResourceManager.GetString("ConsoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The console is now online.
        /// </summary>
        public static string ConsoleOnlineLogMessage {
            get {
                return ResourceManager.GetString("ConsoleOnlineLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Complete.
        /// </summary>
        public static string InitializationCompleteLogMessage {
            get {
                return ResourceManager.GetString("InitializationCompleteLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinClient.InitializeConsole.
        /// </summary>
        public static string InitializeConsoleLogHeader {
            get {
                return ResourceManager.GetString("InitializeConsoleLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Modules.
        /// </summary>
        public static string InitializeModulesLogMessage {
            get {
                return ResourceManager.GetString("InitializeModulesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string ModulesHeader {
            get {
                return ResourceManager.GetString("ModulesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter something to say.
        /// </summary>
        public static string WarningNoChatText {
            get {
                return ResourceManager.GetString("WarningNoChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Search.
        /// </summary>
        public static string WarningNoChatTextHeader {
            get {
                return ResourceManager.GetString("WarningNoChatTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinClient.Loaded.
        /// </summary>
        public static string WinClientLoadedLogHeader {
            get {
                return ResourceManager.GetString("WinClientLoadedLogHeader", resourceCulture);
            }
        }
    }
}
