//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MattEland.Ani.Alfred.VisualStudio.Properties {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MattEland.Ani.Alfred.VisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically starting Alfred.
        /// </summary>
        internal static string AlfredPackageEnsureAlfredInstanceAutoStartingLogMessage {
            get {
                return ResourceManager.GetString("AlfredPackageEnsureAlfredInstanceAutoStartingLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string AlfredPackageInstantiatingAlfredLogHeader {
            get {
                return ResourceManager.GetString("AlfredPackageInstantiatingAlfredLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantiating Alfred.
        /// </summary>
        internal static string AlfredPackageInstantiatingAlfredLogMessage {
            get {
                return ResourceManager.GetString("AlfredPackageInstantiatingAlfredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred Pages.
        /// </summary>
        internal static string AlfredToolWindowCaption {
            get {
                return ResourceManager.GetString("AlfredToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsClient.Initialize.
        /// </summary>
        internal static string AlfredToolWindowControlInitializeLogHeader {
            get {
                return ResourceManager.GetString("AlfredToolWindowControlInitializeLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Window Created.
        /// </summary>
        internal static string AlfredToolWindowControlInitializeLogMessage {
            get {
                return ResourceManager.GetString("AlfredToolWindowControlInitializeLogMessage", resourceCulture);
            }
        }
    }
}
