//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Ani.Alfred.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Ani.Alfred.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now initialized..
        /// </summary>
        internal static string AlfredStatusController_Initialize__ModuleInitialized {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize__ModuleInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred is now Online..
        /// </summary>
        internal static string AlfredStatusController_Initialize_AlfredOnline {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_AlfredOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructed to initialize but system is already online.
        /// </summary>
        internal static string AlfredStatusController_Initialize_ErrorAlreadyOnline {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_ErrorAlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string AlfredStatusController_Initialize_Initializing {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0}.
        /// </summary>
        internal static string AlfredStatusController_Initialize_InitializingModule {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_InitializingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initilization Completed; notifying modules..
        /// </summary>
        internal static string AlfredStatusController_Initialize_InitilizationCompleted {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_InitilizationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.Initialize.
        /// </summary>
        internal static string AlfredStatusController_Initialize_LogHeader {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down completed..
        /// </summary>
        internal static string AlfredStatusController_Shutdown_Completed {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructed to shut down but system is already offline.
        /// </summary>
        internal static string AlfredStatusController_Shutdown_ErrorAlreadyOffline {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_ErrorAlreadyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructed to shut down but system is already shutting down.
        /// </summary>
        internal static string AlfredStatusController_Shutdown_ErrorAlreadyTerminating {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_ErrorAlreadyTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.Shutdown.
        /// </summary>
        internal static string AlfredStatusController_Shutdown_LogHeader {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now offline..
        /// </summary>
        internal static string AlfredStatusController_Shutdown_ModuleOffline {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_ModuleOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        internal static string AlfredStatusController_Shutdown_Shutting_down {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_Shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down {0}.
        /// </summary>
        internal static string AlfredStatusController_Shutdown_ShuttingDownModule {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_ShuttingDownModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouldn&apos;t we be heading to bed soon?.
        /// </summary>
        internal static string AlfredTimeModule_AlfredTimeModule_BedtimeNagMessage {
            get {
                return ResourceManager.GetString("AlfredTimeModule_AlfredTimeModule_BedtimeNagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Module.
        /// </summary>
        internal static string AlfredTimeModule_Name {
            get {
                return ResourceManager.GetString("AlfredTimeModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time is now {0:t}.
        /// </summary>
        internal static string AlfredTimeModule_Update_CurrentTimeDisplayString {
            get {
                return ResourceManager.GetString("AlfredTimeModule_Update_CurrentTimeDisplayString", resourceCulture);
            }
        }
    }
}
