//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Notice: Use of the service proxies that accompany this notice is subject to
//            the terms and conditions of the license agreement located at
//            http://go.microsoft.com/fwlink/?LinkID=202740
//            If you do not agree to these terms you may not use this content.

using System;

namespace MattEland.Ani.Alfred.Search.Bing
{

    public partial class ImageResult
    {

        private Guid _ID;

        private string _Title;

        private string _MediaUrl;

        private string _SourceUrl;

        private string _DisplayUrl;

        private int? _Width;

        private int? _Height;

        private long? _FileSize;

        private string _ContentType;

        private Thumbnail _Thumbnail;

        public Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        public string Title
        {
            get
            {
                return _Title;
            }
            set
            {
                _Title = value;
            }
        }

        public string MediaUrl
        {
            get
            {
                return _MediaUrl;
            }
            set
            {
                _MediaUrl = value;
            }
        }

        public string SourceUrl
        {
            get
            {
                return _SourceUrl;
            }
            set
            {
                _SourceUrl = value;
            }
        }

        public string DisplayUrl
        {
            get
            {
                return _DisplayUrl;
            }
            set
            {
                _DisplayUrl = value;
            }
        }

        public int? Width
        {
            get
            {
                return _Width;
            }
            set
            {
                _Width = value;
            }
        }

        public int? Height
        {
            get
            {
                return _Height;
            }
            set
            {
                _Height = value;
            }
        }

        public long? FileSize
        {
            get
            {
                return _FileSize;
            }
            set
            {
                _FileSize = value;
            }
        }

        public string ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                _ContentType = value;
            }
        }

        public Thumbnail Thumbnail
        {
            get
            {
                return _Thumbnail;
            }
            set
            {
                _Thumbnail = value;
            }
        }
    }
}
