//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Ani.Alfred.Core.Modules.SysMonitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Ani.Alfred.Core.Modules.SysMonitor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU {0}.
        /// </summary>
        internal static string CpuMonitorModule_Cpu_Label_Format {
            get {
                return ResourceManager.GetString("CpuMonitorModule_Cpu_Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Monitor.
        /// </summary>
        internal static string CpuMonitorModule_Name {
            get {
                return ResourceManager.GetString("CpuMonitorModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Monitor.
        /// </summary>
        internal static string DiskMonitorName {
            get {
                return ResourceManager.GetString("DiskMonitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Read %:.
        /// </summary>
        internal static string DiskReadLabel {
            get {
                return ResourceManager.GetString("DiskReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Write %:.
        /// </summary>
        internal static string DiskWriteLabel {
            get {
                return ResourceManager.GetString("DiskWriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory:.
        /// </summary>
        internal static string MemoryMonitorModule_LabelName {
            get {
                return ResourceManager.GetString("MemoryMonitorModule_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Monitor.
        /// </summary>
        internal static string MemoryMonitorModule_Name {
            get {
                return ResourceManager.GetString("MemoryMonitorModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Monitoring.
        /// </summary>
        internal static string SystemMonitoringSystem_Name {
            get {
                return ResourceManager.GetString("SystemMonitoringSystem_Name", resourceCulture);
            }
        }
    }
}
