//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Ani.Alfred.Core.Speech {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Ani.Alfred.Core.Speech.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for installed voice modules.
        /// </summary>
        internal static string FindVoiceModules {
            get {
                return ResourceManager.GetString("FindVoiceModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unknown voice with no voice information.
        /// </summary>
        internal static string UnknownVoiceFound {
            get {
                return ResourceManager.GetString("UnknownVoiceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using unknown voice. Speech synthesis may not function properly..
        /// </summary>
        internal static string UsingUnknownVoice {
            get {
                return ResourceManager.GetString("UsingUnknownVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using voice: {0}.
        /// </summary>
        internal static string UsingVoiceLog {
            get {
                return ResourceManager.GetString("UsingVoiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found voice: {0} ({1} {2}) Enabled: {3}.
        /// </summary>
        internal static string VoiceFoundList {
            get {
                return ResourceManager.GetString("VoiceFoundList", resourceCulture);
            }
        }
    }
}
