//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MattEland.Ani.Alfred.Core.Speech {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MattEland.Ani.Alfred.Core.Speech.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for installed voice modules.
        /// </summary>
        internal static string FindVoiceModules {
            get {
                return ResourceManager.GetString("FindVoiceModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing speech module....
        /// </summary>
        internal static string InitializingSpeechModule {
            get {
                return ResourceManager.GetString("InitializingSpeechModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unknown voice with no voice information.
        /// </summary>
        internal static string UnknownVoiceFound {
            get {
                return ResourceManager.GetString("UnknownVoiceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using unknown voice. Speech synthesis may not function properly..
        /// </summary>
        internal static string UsingUnknownVoice {
            get {
                return ResourceManager.GetString("UsingUnknownVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using voice: {0}.
        /// </summary>
        internal static string UsingVoiceLog {
            get {
                return ResourceManager.GetString("UsingVoiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found voice: {0} - {1} {2} Enabled: {3}.
        /// </summary>
        internal static string VoiceFoundList {
            get {
                return ResourceManager.GetString("VoiceFoundList", resourceCulture);
            }
        }
    }
}
