//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Notice: Use of the service proxies that accompany this notice is subject to
//            the terms and conditions of the license agreement located at
//            http://go.microsoft.com/fwlink/?LinkID=202740
//            If you do not agree to these terms you may not use this content.

using System;

namespace MattEland.Ani.Alfred.Search.Bing
{

    public partial class Thumbnail
    {

        private string _MediaUrl;

        private string _ContentType;

        private int? _Width;

        private int? _Height;

        private long? _FileSize;

        public string MediaUrl
        {
            get
            {
                return _MediaUrl;
            }
            set
            {
                _MediaUrl = value;
            }
        }

        public string ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                _ContentType = value;
            }
        }

        public int? Width
        {
            get
            {
                return _Width;
            }
            set
            {
                _Width = value;
            }
        }

        public int? Height
        {
            get
            {
                return _Height;
            }
            set
            {
                _Height = value;
            }
        }

        public long? FileSize
        {
            get
            {
                return _FileSize;
            }
            set
            {
                _FileSize = value;
            }
        }
    }
}
