//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattEland.Ani.Alfred.Core.Definitions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MattEland.Ani.Alfred.Core.Definitions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was already offline when told to shut down..
        /// </summary>
        internal static string AlfredComponent_ShutdownAlreadyOffline {
            get {
                return ResourceManager.GetString("AlfredComponent_ShutdownAlreadyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred Control.
        /// </summary>
        internal static string AlfredControlSubSystem_Name {
            get {
                return ResourceManager.GetString("AlfredControlSubSystem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred Provider has not been set.
        /// </summary>
        internal static string AlfredCoreModule_AlfredNotSet {
            get {
                return ResourceManager.GetString("AlfredCoreModule_AlfredNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently {1}.
        /// </summary>
        internal static string AlfredCoreModule_AlfredStatusText {
            get {
                return ResourceManager.GetString("AlfredCoreModule_AlfredStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Power.
        /// </summary>
        internal static string AlfredCoreModule_Name {
            get {
                return ResourceManager.GetString("AlfredCoreModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was offline when told to update..
        /// </summary>
        internal static string AlfredItemOfflineButToldToUpdate {
            get {
                return ResourceManager.GetString("AlfredItemOfflineButToldToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was already online when told to initialize..
        /// </summary>
        internal static string AlfredModule_InitializeAlreadyOnline {
            get {
                return ResourceManager.GetString("AlfredModule_InitializeAlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules may not contain null entries..
        /// </summary>
        internal static string AlfredProvider_AddModules_ErrorNullModule {
            get {
                return ResourceManager.GetString("AlfredProvider_AddModules_ErrorNullModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred must be offline in order to add components..
        /// </summary>
        internal static string AlfredProvider_AssertMustBeOffline_ErrorNotOffline {
            get {
                return ResourceManager.GetString("AlfredProvider_AssertMustBeOffline_ErrorNotOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.
        /// </summary>
        internal static string AlfredProvider_Name {
            get {
                return ResourceManager.GetString("AlfredProvider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred must be online in order to update modules..
        /// </summary>
        internal static string AlfredProvider_Update_ErrorMustBeOnline {
            get {
                return ResourceManager.GetString("AlfredProvider_Update_ErrorMustBeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructed to initialize but system is already online.
        /// </summary>
        internal static string AlfredStatusController_Initialize_ErrorAlreadyOnline {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_ErrorAlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.Initialize.
        /// </summary>
        internal static string AlfredStatusController_Initialize_LogHeader {
            get {
                return ResourceManager.GetString("AlfredStatusController_Initialize_LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred.Shutdown.
        /// </summary>
        internal static string AlfredStatusController_Shutdown_LogHeader {
            get {
                return ResourceManager.GetString("AlfredStatusController_Shutdown_LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subsystems Detected.
        /// </summary>
        internal static string AlfredSubSystemListModule_NoSubsystemsDetected {
            get {
                return ResourceManager.GetString("AlfredSubSystemListModule_NoSubsystemsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouldn&apos;t we be heading to bed soon?.
        /// </summary>
        internal static string AlfredTimeModule_AlfredTimeModule_BedtimeNagMessage {
            get {
                return ResourceManager.GetString("AlfredTimeModule_AlfredTimeModule_BedtimeNagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Date.
        /// </summary>
        internal static string AlfredTimeModule_Name {
            get {
                return ResourceManager.GetString("AlfredTimeModule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time is now {0:t}.
        /// </summary>
        internal static string AlfredTimeModule_Update_CurrentTimeDisplayString {
            get {
                return ResourceManager.GetString("AlfredTimeModule_Update_CurrentTimeDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is now online.
        /// </summary>
        internal static string AppOnlineLogMessage {
            get {
                return ResourceManager.GetString("AppOnlineLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to click the button when CanExecute on ClickCommand returned false..
        /// </summary>
        internal static string ButtonWidgetClickCantExecuteErrorMessage {
            get {
                return ResourceManager.GetString("ButtonWidgetClickCantExecuteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Subsystem: {0}, Command: {1}, Data: {2}}}.
        /// </summary>
        internal static string ChatCommandToString {
            get {
                return ResourceManager.GetString("ChatCommandToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatModuleName {
            get {
                return ResourceManager.GetString("ChatModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an exception raising a property changed event: {0}.
        /// </summary>
        internal static string ComponentBasePropertyChangedException {
            get {
                return ResourceManager.GetString("ComponentBasePropertyChangedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        internal static string InitializeButtonText {
            get {
                return ResourceManager.GetString("InitializeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component is not currently attached to an Alfred instance.
        /// </summary>
        internal static string NoAlfredInstance {
            get {
                return ResourceManager.GetString("NoAlfredInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfred Provider has not been set.
        /// </summary>
        internal static string NoAlfredText {
            get {
                return ResourceManager.GetString("NoAlfredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down.
        /// </summary>
        internal static string ShutdownButtonText {
            get {
                return ResourceManager.GetString("ShutdownButtonText", resourceCulture);
            }
        }
    }
}
